# test this goreleaser config with:
# - cd chisel
# - goreleaser --skip-publish --rm-dist --config .github/goreleaser.yml
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/jpillora/chisel/share.BuildVersion={{.Version}}
    flags:
      - -trimpath
    goos:
      - android
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
archives:
  - format: gz
    files:
      - none*
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
